dices/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('speechdb.urls')),
    path('admin/', admin.site.urls)
]

speechdb/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from . import views

frontend_urls = ([
    path('', views.AppSpeechList.as_view(), name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='speechdb/login.html'), name='login'),
    path('logout/', auth_views.logout_then_login, {'login_url':'app:index'}, name='logout'),
    path('meta/', views.AppMetadataList.as_view(), name='meta'),
    path('authors/', views.AppAuthorList.as_view(), name='authors'),
    path('authors/csv/', views.AppAuthorCSV.as_view(), name='authors_csv'),
    path('author/<str:public_id>', views.AppAuthorDetail.as_view(), name="author_detail"),
    path('works/', views.AppWorkList.as_view(), name='works'),
    path('works/csv/', views.AppWorkCSV.as_view(), name="works_csv"),
    path('work/<str:public_id>', views.AppWorkDetail.as_view(), name="work_detail"),
    path('characters/', views.AppCharacterList.as_view(), name='characters'),
    path("characters/csv/", views.AppCharacterCSV.as_view(), name="characters_csv"),
    path('character/<str:public_id>/', views.AppCharacterDetail.as_view(), name='character_detail'),
    path('instances/', views.AppCharacterInstanceList.as_view(), name='instances'),
    path("instances/csv/", views.AppCharacterInstanceCSV.as_view(), name="instances_csv"),
    path('characterinstance/<str:public_id>', views.AppCharacterInstanceDetail.as_view(), name='instance_detail'),
    path('clusters/', views.AppSpeechClusterList.as_view(), name='clusters'),
    path("clusters/csv/", views.AppSpeechClusterCSV.as_view(), name="clusters_csv"),
    path('speechcluster/<str:public_id>/', views.AppSpeechClusterDetail.as_view(), name='cluster_detail'),
    path('speeches/', views.AppSpeechList.as_view(), name='speeches'),
    path('speeches/csv/', views.AppSpeechCSV.as_view(), name='speeches_csv'),
    path('speech/<str:public_id>/', views.AppSpeechDetail.as_view(), name="speech_detail"),
], 'app')

api_urls = ([
    path('meta/', views.MetadataList.as_view()),
    path('authors/', views.AuthorList.as_view()),
    path('authors/<int:pk>/', views.AuthorDetail.as_view()),
    path('works/', views.WorkList.as_view()),
    path('works/<int:pk>/', views.WorkDetail.as_view()),
    path('characters/', views.CharacterList.as_view()),
    path('characters/<int:pk>/', views.CharacterDetail.as_view()),
    path('instances/', views.CharacterInstanceList.as_view()),
    path('instances/<int:pk>/', views.CharacterInstanceDetail.as_view()),
    path('speeches/', views.SpeechList.as_view()),
    path('speeches/<int:pk>/', views.SpeechDetail.as_view()),
    path('clusters/', views.SpeechClusterList.as_view()),
    path('clusters/<int:pk>/', views.SpeechClusterDetail.as_view()),
], 'api')

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='app:index')),
    path('app/', include(frontend_urls)),
    path('api/', include(api_urls)),
]

speechdb/models.py
from django.db import models, IntegrityError
from django.utils.functional import cached_property
import secrets

URN_BASE = "https://db.dices.mta.ca/app"

class PublicIdModel(models.Model):
    '''a base class that incorporates a public-facing unique id in all records
        - every new record gets a `public_id` field, a four-digit hex code
        - this is suitable for generating record-specific URNs
    '''

    # expect four character string
    public_id = models.CharField(max_length=4, unique=True, editable=False)
        
    class Meta:
         abstract = True
    
    @property
    def dices_urn(self):
        '''return a urn for the object using project namespace'''
        
        return f"{URN_BASE}/{self.__class__.__name__}/{self.public_id}"
    
    
    # overload the save method to generate a unique public_id value
    def save(self, *args, **kwargs):
        if not self.public_id:
            for _ in range(100):
                
                # generate four-digit hex
                candidate = f"{secrets.randbits(16):04X}"
                if not type(self).objects.filter(public_id=candidate).exists():
                    self.public_id = candidate
                    break
            else:
                raise IntegrityError("No available unique public_id after 100 attempts")
        super().save(*args, **kwargs)

# Metadata about the database itself
class Metadata(PublicIdModel):
    name = models.CharField(max_length=128, blank=False, unique=True)
    value = models.TextField()

# Entity classes

class Author(PublicIdModel):
    '''An ancient author'''
    
    name = models.CharField(max_length=128)
    wd = models.CharField('WikiData ID', max_length=32, blank=True, default="")
    urn = models.CharField(max_length=128, blank=True, default="")
    
    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name


class Work(PublicIdModel):
    '''An epic text'''

    class Language(models.TextChoices):
        GREEK = ('greek', 'Greek')
        LATIN = ('latin', 'Latin')
        
    title = models.CharField(max_length=128)
    wd = models.CharField('WikiData ID', max_length=32, blank=True, default="")
    tlg = models.CharField(max_length=12, blank=True, default="")
    urn = models.CharField(max_length=128, blank=True, default="")
    author = models.ForeignKey(Author, on_delete=models.PROTECT)
    lang = models.CharField(max_length=8, choices=Language.choices)
    
    class Meta:
        ordering = ['author', 'title']


    def __str__(self):
        return self.get_long_name()

    
    def get_long_name(self):
        '''Return common name as a string'''
        if self.author.name == "Anonymous":
            return self.title
        else:
            return f'{self.author.name}, {self.title}'


class Character(PublicIdModel):
    '''An epic character'''
    
    class CharacterNumber(models.TextChoices):
        INDIVIDUAL = ('individual', 'Individual')
        COLLECTIVE = ('collective', 'Collective')


    class CharacterBeing(models.TextChoices):
        MORTAL = ('mortal', 'Mortal')
        DIVINE = ('divine', 'Divine')
        CREATURE = ('creature', 'Mythical Creature')
        OTHER = ('other', 'Other')
        

    class CharacterGender(models.TextChoices):
        MALE = ('male', 'Male')
        FEMALE = ('female', 'Female')
        NB = ('x', 'Mixed/non-binary')
        NA = ('none', 'Unknown/not-applicable')

    name = models.CharField(max_length=128)
    being = models.CharField(max_length=16, choices=CharacterBeing.choices,
            default=CharacterBeing.MORTAL)
    number = models.CharField(max_length=16, choices=CharacterNumber.choices,
            default=CharacterNumber.INDIVIDUAL)
    gender = models.CharField(max_length=16, choices=CharacterGender.choices,
            default=CharacterGender.NA)
    wd = models.CharField('WikiData ID', max_length=32, blank=True, default="")
    manto = models.CharField('MANTO ID', max_length=32, blank=True, default="")
    tt = models.CharField('ToposText ID', max_length=32, blank=True, default="")
    notes = models.CharField('Notes', max_length=256, blank=True, default="")

    class Meta:
        ordering = ['name']


    def __str__(self):
        return self.name
        
    def get_speeches(self):
        return Speech.objects.filter(spkr__char__id=self.id)

    def get_addresses(self):
        return Speech.objects.filter(addr__char__id=self.id)


class CharacterInstance(PublicIdModel):
    '''A character engaged in a speech'''

    name = models.CharField(max_length=128)
    display = models.CharField(max_length=128)
    being = models.CharField(max_length=16, 
            choices=Character.CharacterBeing.choices,
            default=Character.CharacterBeing.MORTAL)
    number = models.CharField(max_length=16,
            choices=Character.CharacterNumber.choices,
            default=Character.CharacterNumber.INDIVIDUAL)
    gender = models.CharField(max_length=16,
            choices=Character.CharacterGender.choices,
            default=Character.CharacterGender.NA)
    char = models.ForeignKey(Character, related_name='instances',
            null=True, blank=True, on_delete=models.SET_NULL)
    disguise = models.CharField(max_length=128, blank=True, default="")
    anon = models.BooleanField(default=False)
    notes = models.CharField(max_length=256, blank=True, default="")
    context = models.CharField(max_length=128)
    
    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.get_long_name()
    
    def get_long_name(self):
        '''returns char name, including instance name and/or disguise'''
        name = self.name
        
        if self.char is not None:
            if name != self.char.name:
                name += '/' + self.char.name
        
        return f"{name} ({self.context})"
    
    def get_speeches(self):
        '''returns set of speeches by all instances of underlying char'''
        return Speech.objects.filter(spkr__char=self.char)
    
    def get_addresses(self):
        '''returns set of speeches by all instances of underlying char'''
        return Speech.objects.filter(addr__char=self.char)


class SpeechCluster(PublicIdModel):
    '''A group of related speeches'''
    
    class Meta:
        ordering = ['seq']

    seq = models.IntegerField(default=0)
    
    @cached_property
    def _speeches(self):
        return list(self.speeches.all())

    @cached_property
    def work(self):
        return self._speeches[0].work if self._speeches else None
                
    @cached_property
    def speakers(self):
        s=set()
        for sp in self._speeches: s.update(sp.spkr.all())
        return tuple(s)    

    @cached_property
    def addressees(self):
        s=set()
        for sp in self._speeches: s.update(sp.addr.all())
        return tuple(s) 

    def get_spkr_str(self, sep=", "):
        '''Return speaker list as a string'''
        return sep.join(sorted(map(str, self.speakers)))    

    def get_addr_str(self, sep=", "):
        '''Return addressee list as a string'''
        return sep.join(sorted(map(str, self.addressees)))        

    def get_chars_str(self, sep=", "):
        '''Return list of all participants as a string'''
        chars = set(self.speakers + self.addressees)
        return sep.join(sorted(map(str, chars)))
                
    def get_urn(self):
        '''Return CTS URN for the whole cluster'''
            
        work = self.work
        if work is None or work.urn is None:
            return None
        
        urn = work.urn
        l_fi = self._speeches[0].l_fi
        l_la = self._speeches[-1].l_la
        
        return f'{urn}:{l_fi}-{l_la}'

    def get_loc_str(self):
        '''Return line range of conversation as a string'''

        work = self.work
        if work is None:
            return None
        
        long_name = work.get_long_name()
        l_fi = self._speeches[0].l_fi
        l_la = self._speeches[-1].l_la
        return f'{long_name} {l_fi}–{l_la}'
        

class Speech(PublicIdModel):
    '''A direct speech instance'''
    
    class SpeechType(models.TextChoices):
        SOLILOQUY = ('S', 'Soliloquy')
        MONOLOGUE = ('M', 'Monologue')
        DIALOGUE = ('D', 'Dialogue')
        GENERAL = ('G', 'General')
    
    cluster = models.ForeignKey(SpeechCluster, related_name='speeches', on_delete=models.CASCADE)
    work = models.ForeignKey(Work, on_delete=models.PROTECT)
    type = models.CharField(max_length=1, choices=SpeechType.choices)
    seq = models.IntegerField()
    l_fi = models.CharField('first line', max_length=16)
    l_la = models.CharField('last line', max_length=16)
    spkr = models.ManyToManyField(CharacterInstance, related_name='speeches')
    addr = models.ManyToManyField(CharacterInstance, related_name='addresses', blank=True, default="")
    spkr_notes = models.CharField(max_length=256, blank=True, default="")
    addr_notes = models.CharField(max_length=256, blank=True, default="")
    part = models.IntegerField()
    level = models.IntegerField(default=0)
    notes = models.CharField(max_length=256, blank=True, default="")
    
    class Meta:
        ordering = ['work', 'seq']
    
    def __str__(self):
        return f'{self.work} {self.l_fi}-{self.l_la}'
        
    def get_urn(self):
        '''Return CTS URN for the whole speech'''
        if self.work.urn:
            return f'{self.work.urn}:{self.l_fi}-{self.l_la}'
        
    def get_spkr_str(self):
        '''Return speaker list as a string'''
        return ', '.join([str(s) for s in self.spkr.all()])
    
    def get_addr_str(self):
        '''Return speaker list as a string'''
        return ', '.join([str(s) for s in self.addr.all()])
        
    def get_short_type(self):
        '''Return one-char type designation'''
        t = self.type
        if t == 'D' or t == 'G':
            t += str(self.part)
        return t

speechdb/templates/speechdb/author_detail.html
{% extends "speechdb/base_nosidebar.html" %}

{% block title %}Author Detail{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="accordion">
    <div class="accordion-item">
			<div class="accordion-header" style="padding: 20px 20px">
      <h4>Author Detail</h4>
			<small>Author {{ author.public_id }}</small>
      <div class="accordion-body">
        <table class="table">
          <thead>
          </thead>
          <tbody>
            <tr>
              <td>name</td>
              <td>{{ author.name}}</td>
            </tr>
            <tr>
              <td>CITE URN</td>
              <td>
                {% if author.urn %}
                {{ author.urn }}
                <a style="margin-left:0.5em" href="https://catalog.perseus.org/catalog/{{ author.urn }}">
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>                  
                </a>
                {% endif %}
              </td>
            </tr>
            <tr>
              <td>WikiData</td>
              <td>
                {% if author.wd %}
                {{ author.wd }}
                <a style="margin-left:0.5em" href="https://www.wikidata.org/wiki/{{ author.wd }}">
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                </a>
                {% endif %}
              </td>
            </tr>
          </tbody>
      </table>
    </div>
  </div>    
</div>
{% endblock %}

speechdb/templates/speechdb/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Font Awesome -->
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
		<!-- Include jQuery & Select2 -->
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
		<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
		<!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
		<!-- DICES style -->
    <link href="{% static 'speechdb/style.css' %}" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static 'speechdb/dices.png' %}"/>
		<!-- Select2 functionality -->
		<script src="{% static 'speechdb/dices.js' %}"></script>
    <title>{% block title %}DICES{% endblock %}</title>
  </head>
  <body class="d-flex flex-column vh-100">

    <nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="https://dices.mta.ca">
          DICES
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"  data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
					
          <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="https://dices.mta.ca" >Project Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="https://db.dices.mta.ca" >Database</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://book.dices.mta.ca" >Digital Appendix</a>
            </li>
					</ul>
        </div>
      </div>
    </nav>
    <div id="content" class="container-fluid flex-grow-1 p-3 d-flex flex-column">
    {% block body %}
    {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

speechdb/templates/speechdb/base_nosidebar.html
{% extends "speechdb/base.html" %}

{% block body %}
<div id="detailContainer" class="col h-100 overflow-auto flex-grow-1 position-relative">
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

speechdb/templates/speechdb/character_detail.html
{% extends "speechdb/base_nosidebar.html" %}

{% block title %}Character Detail{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="accordion">
    <div class="accordion-item">
			<div class="accordion-header" style="padding: 20px 20px">
      <h4>Character Detail</h4>
			<small>Character {{ char.public_id }}</small>
      <div class="accordion-body">
        <table class="table">
          <thead>
          </thead>
          <tbody>
            <tr>
              <td>name</td>
              <td>{{ char.name}}</td>
            </tr>
            <tr>
              <td>being</td>
              <td>{{ char.being }}</td>
            </tr>
            <tr>
              <td>gender</td>
              <td>{{ char.gender }}</td>
            </tr>
            <tr>
              <td>number</td>
              <td>{{ char.number }}</td>
            </tr>
            <tr>
              <td>speeches as speaker:</td>
              <td>
                {{ char.get_speeches.count }}
                <a style="margin-left: 1em" href="{% url 'app:speeches' %}?spkr_char_pubid={{ char.public_id }}">
                  <i class="fa-solid fa-magnifying-glass"></i>
                </a>
              </td>
            </tr>
            <tr>
              <td>speeches as addressee:</td>
              <td>
                {{ char.get_addresses.count }}
                <a style="margin-left: 1em" href="{% url 'app:speeches' %}?addr_char_pubid={{ char.public_id }}">
                  <i class="fa-solid fa-magnifying-glass"></i>
                </a>
              </td>
            </tr>
            <tr>
              <td>MANTO</td>
              <td>
                {% if char.manto %}
                {{ char.manto }}
                <a style="margin-left:0.5em" href="https://resource.manto.unh.edu/{{ char.manto }}">
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>                  
                </a>
                {% endif %}
              </td>
            </tr>
            <tr>
              <td>WikiData</td>
              <td>
                {% if char.wd %}
                {{ char.wd }}
                <a style="margin-left:0.5em" href="https://www.wikidata.org/wiki/{{ char.wd }}">
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                </a>
                {% endif %}
              </td>
            </tr>
            <tr>
              <td>ToposText</td>
              <td>
                {% if char.tt %}
                {{ char.tt }}
                <a style="margin-left:0.5em" href="https://topostext.org/people/{{ char.tt }}">
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                </a>
                {% endif %}
              </td>
            </tr>
            
          </tbody>
      </table>
    </div>
  </div>    
  <div class="accordion-item">
	<h5 class="accordion-header" style="padding:20px 20px">Instances</h5>
      <div class="accordion-body">
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Context</th>
              <th>Speaker</th>
              <th>Addressee</th>
            </tr>
          </thead>
          <tbody>
            {% for inst in char.instances.all %}
            <tr>
              <td>
                {{ inst.name }}
                <a href="{% url 'app:instance_detail' inst.public_id %}">
                  <i class="fa-solid fa-circle-info"></i>
                </a>
              </td>
              <td>{{ inst.context }}</td>
              <td>
                {{ inst.speeches.count }}
                <a style="margin-left: 1em" href="{% url 'app:speeches' %}?spkr_inst_pubid={{ inst.public_id }}">
                  <i class="fa-solid fa-magnifying-glass"></i>
                </a>
              </td>
              <td>
                {{ inst.addresses.count }}
                <a style="margin-left: 1em" href="{% url 'app:speeches' %}?addr_inst_pubid={{ inst.public_id }}">
                  <i class="fa-solid fa-magnifying-glass"></i>
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

speechdb/templates/speechdb/characters.html
{% extends "speechdb/results.html" %}

{% block title %}Characters{% endblock %}
{% block sidebar_title %}Characters{% endblock %}
{% block sidebar_desc %}
<p>
  Core identities of speakers and addressees. External ID columns link to entries in the respective databases.
</p>
{% endblock %}

{% block results %}
<table class="table table-striped">
  <thead>
    <tr><th>Name</th><th>WikiData ID</th><th>MANTO ID</tr>
  </thead>
  <tbody>
    {% for c in page %}
    <tr>
      <td>{{ c.name }}</td>
      <td><a href="https://www.wikidata.org/wiki/{{ c.wd }}">{{ c.wd }}</a></td>
      <td>
        {% if c.manto %}
        <a href="https://yayalu.github.io/greekgraphs/#/datacards?id={{ c.manto }}">{{ c.manto }}</a>
        {% else %}
        {{ c.manto }}
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

speechdb/templates/speechdb/clusters.html
{% extends "speechdb/results.html" %}

{% block title %}Speech Clusters{% endblock %}
{% block sidebar_title %}Speech Clusters{% endblock %}
{% block sidebar_desc %}
<p>
  Clusters group speeches related by a common continuous interaction between characters.
</p>
{% endblock %}

{% block results %}
<table class="table table-striped">
  <thead>
    <tr><th>Loci</th><th>Type</th><th>Parts</th><th>Characters</th></tr>
  </thead>
  <tbody>
    {% for c in page %}
    <tr>
      <td>{{ c.work.get_long_name }} {{ c.speech_set.first.l_fi }}—{{ c.speech_set.last.l_la }}</a></td>
      <td>{{ c.get_long_type }}</td>
      <td style="text-align:right">
        <a href="{% url 'speechdb:search' %}?cluster_id={{ c.pk }}">{{ c.speech_set.count }}</a>
      </td>
      <td>{{ c.get_chars_str }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

speechdb/templates/speechdb/default_form.html
<div class="form-group">
	{% for field in form %}
	{% if not field.is_hidden %}
	<div class="row">
		<div class="col">
			{{ field.label_tag }}
			{{ field }}
		</div>
	</div>
	{% else %}
	{{ field }}
	{% endif %}
	{% endfor %}
</div>

speechdb/templates/speechdb/speech_list.html
{% extends "speechdb/results.html" %}

{% block title %}Speeches{% endblock %}

{% block results %}
<table class="table table-striped">
  <thead>
    <tr>
      <th>Locus</th>
      <th>Speaker</th>
      <th>Addressee</th>
      <th>Type</th>
      <th style="width:6em">Turn</th>
      <th>Tags</th>
      <th>Embedded</th>
    </tr>
  </thead>
  <tbody>
    {% for s in object_list %}
    <tr>
      <td>
          {{ s.work.get_long_name }} {{ s.l_fi }}—{{ s.l_la }}
          <a style="margin-left:0.5em" href="{% url 'app:speech_detail' s.public_id %}">
              <i class="fa-solid fa-circle-info"></i>
          </a>
          {% if s.get_urn %}
          <a style="margin-left:0.5em" href="{{ reader }}{{ s.get_urn }}">
              <i class="fa-solid fa-arrow-up-right-from-square"></i>
          </a>          
          {% endif %}
      </td>
      <td>
        {% for inst in s.spkr.all %}
        <div>
          {{ inst.display }}
          <a style="margin-left:0.5em" href="{% url 'app:instance_detail' inst.public_id %}">
              <i class="fa-solid fa-circle-info"></i>
          </a>
        </div>
        {% endfor %}
      </td>
      <td>
        {% for inst in s.addr.all %}
        <div>
            {{ inst.display }}            
            <a style="margin-left:0.5em" href="{% url 'app:instance_detail' inst.public_id %}">
                <i class="fa-solid fa-circle-info"></i>            
            </a>
        </div>
        {% endfor %}
      </td>
      <td>
        {{ s.type }}
      </td>
      <td>
          {{ s.part }} of {{ s.cluster_size }}
          <a style="margin-left: 1em" href="{% url 'app:cluster_detail' s.cluster.public_id %}">
              <i class="fa-solid fa-circle-info"></i>
          </a>
      </td>
      <td class="small">
        {% for tag in s.tags.all %}
          <span class="badge bg-secondary">{{ tag.get_type_display }}</span><br>
        {% endfor %}
      </td>
      <td>
        {{ s.level }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

{% block filters %}
  <div class="card small mb-2">
    <div class="card-header" id="hdr_speaker">
      <span>Speaker Properties</span>
    </div>
    <div class="card-body" id="collapse_speaker" aria-labelledby="hdr_speaker">
			{% include "speechdb/default_form.html" with form=spkr_character_form %}
			<div class="form-group">
				<div class="row mt-2">
					<div class="col-sm-7">
						{{ spkr_instance_form.inst_anon.label_tag }}
					</div>
					<div class="col-sm-5">
						{{ spkr_instance_form.inst_anon }}
					</div>
				</div>
				<div class="row mt-2">
					<div class="col-sm-7">
						{{ spkr_instance_form.inst_disguised.label_tag }}
					</div>
					<div class="col-sm-5">
						{{ spkr_instance_form.inst_disguised }}
					</div>
				</div>
			</div>			
    </div>
  </div>
  <div class="card small mb-2">
    <div class="card-header" id="hdr_addressee">
      <span>Addressee Properties</span>
    </div>
    <div class="card-body" id="collapse_addressee" aria-labelledby="hdr_addressee">
			{% include "speechdb/default_form.html" with form=addr_character_form %}
    </div>
  </div>
  <div class="card small mb-2">
    <div class="card-header">
      <span>Conversation properties</span>
    </div>
		<div class="card-body">
			{% include "speechdb/speech_form.html" with form=speech_form %}
		</div>
  </div>
  <div class="card small mb-2">
    <div class="card-header">
      <span>Text properties</span>
    </div>
    <div class="card-body">
			{% include "speechdb/default_form.html" with form=text_form %}
    </div>
  </div>
{% endblock %}